### ISSUE TITLE
April Objectives

### ISSUE THREAD

**Issue by rocketstack-matt** [finos-labs/architecture-as-code#93]
* Create first published CALM release
  - [x] Introduce interfaces - #48
  - [ ] External architecture references = #111 
  - [ ] Publish to Schema store - #5
  - [ ] Pattern repo (public + private repo support) - #69
  
* CLI 
  - [ ] Pattern instantiation - #72
  - [ ] Complete integration with validators - #73
  - [ ] Publish to NPM @aidanm3341 - #99 
  
* Spectral + JSON Schema validation
  - [ ] Spectral ruleset for patterns - #95
  - [ ] Output to test format to integrate with CI tools - #98

* Visualiser
  - [ ] #100
  - [ ] #103 
 
* Docs @rocketstack-matt 
  - [ ] #113
  - [ ] #114
  - [ ] #115
